kind: Deployment
apiVersion: apps/v1
metadata:
   name: webapp
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: webapp
   template:
      metadata:
        labels:
          app: webapp
      spec:
       containers:
        - name: webapp
          image: vishal7500/test    # it will pull the latest image form the dockerhub
          imagePullPolicy: Always     # pull policy specifies to pull the image or use  local image
          ports:
          - containerPort: 9090
