kind: Service                             
apiVersion: v1
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
    - port: 9090                               
      targetPort: 9090                    
      NodePort: 31200
  selector:
    app: webapp                    
  type: LoadBalancer