version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: sudo apt-get install -y ssh
      - add_ssh_keys
      - run:
          name: Deploy Over SSH
          command: ssh -o StrictHostKeyChecking=no ubuntu@172.31.2.140
            
            
      
workflows:
  sample:
    jobs:
      - build-and-test

