version: 2.1


jobs:
  deploy:
    machine: true
    steps:
      
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2d:4a:02:c1:28:6b:7d:7f:48:a3:5a:df:3b:1d:50:23"
      - run:
          name: Sending Dockerfile To Ansible Server
          command: rsync -ravz --delete /home/circleci/project/* ubuntu@184.169.212.155:.
      - run:
          name: Build Dokcer Image
          command: ssh -o StrictHostKeyChecking=no ubuntu@184.169.212.155 docker build -t test:${CIRCLE_BUILD_NUM} .
      - run:

          name: Docker Image Tagging
          command: ssh -o StrictHostKeyChecking=no ubuntu@184.169.212.155 docker image tag test:${CIRCLE_BUILD_NUM} vishal7500/test:${CIRCLE_BUILD_NUM};
                  ssh -o StrictHostKeyChecking=no ubuntu@184.169.212.155 docker image tag test:${CIRCLE_BUILD_NUM} vishal7500/test:latest;
      - run: 
          name: Docker Image Push
          command: ssh -o StrictHostKeyChecking=no ubuntu@184.169.212.155 docker login --username vishal7500 --password $DOCKERHUB_PASSWORD ;
                    ssh -o StrictHostKeyChecking=no ubuntu@184.169.212.155 docker push vishal7500/test:${CIRCLE_BUILD_NUM};
                    ssh -o StrictHostKeyChecking=no ubuntu@184.169.212.155 docker push vishal7500/test:latest;
                    ssh -o StrictHostKeyChecking=no ubuntu@184.169.212.155 docker rmi  -f vishal7500/test:latest  vishal7500/test:${CIRCLE_BUILD_NUM};
      - run:
          name: Copy Files form ansible to Kubernetes Server
          command: rsync -ravz --delete /home/circleci/project/* ubuntu@13.57.219.200:.

      # - run:
      #     name: Kubernetes Deployment Using Ansible Server
      #     command: ssh -o StrictHostKeyChecking=no ubuntu@184.169.212.155 sudo ansible-playbook ansible.yaml
orbs:
  jira: circleci/jira@1.3.1   
    
workflows:
  sample:
    jobs:
      - deploy
      
            
