version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.3.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ubuntu"
      - run:
          name: Deploy code to server
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@172.31.2.140 
            scp /var/lib/jenkins/workspace/test/* ubuntu@172.31.2.140:/home/ubuntu
            ssh -o StrictHostKeyChecking=no ubuntu@172.31.2.140 ls

