version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.3.0
    # steps:
    #   - ssh-tunnel/setup:
    #       key_fingerprint: '2d:4a:02:c1:28:6b:7d:7f:48:a3:5a:df:3b:1d:50:23' 
    #       timeout: 30 
    #       from_host: '172.31.2.140'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2d:4a:02:c1:28:6b:7d:7f:48:a3:5a:df:3b:1d:50:23"
      - run:
          name: Deploy code to server
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@172.31.2.140 
            scp /var/lib/jenkins/workspace/test/* ubuntu@172.31.2.140:/home/ubuntu
            ssh -o StrictHostKeyChecking=no ubuntu@172.31.2.140 touch /home/ubuntu/vishall

