version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
    
      - add_ssh_keys:
          fingerprints:
            - "ansible"
      - run:
          name: Deploy code to server
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@172.31.2.140 
            scp /var/lib/jenkins/workspace/test/* ubuntu@172.31.2.140:/home/ubuntu
            ssh -o StrictHostKeyChecking=no ubuntu@172.31.2.140 touch /home/ubuntu/hghgh
            

