version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      # Install SSH client
      - run: sudo apt-get install -y ssh

      # Add SSH key
      - add_ssh_keys

      # SSH into server and run command
      - run:
          name: Run Remote Command
          command: ssh ubuntu@172.31.2.140 'touch /home/ubuntu/test.txt'

